version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c listen_addresses='*' -c shared_preload_libraries=pg_stat_statements
    networks:
      - backend-network  # Добавить подключение к сети
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d mydb" ]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  backend-network:  # Новая сеть для взаимодействия сервисов
    driver: bridge