app:
  schema-name: &schema-name time_tracker_schema
spring:
  application:
    name: FirstPetProjectTimeTracker

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

      ddl-auto: update
    properties:
      hibernate:
        default_schema: *schema-name
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb?currentSchema=time_tracker_schema
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
server:
  port: 8080